module ChatApp {
   interface ChatCallback {
      void callback(in string message);
   };
   interface Chat {
      boolean say(in ChatCallback objref, in string message);
      boolean join(in ChatCallback objref, in string nickname);
      boolean leave(in ChatCallback objref);
      boolean list(in ChatCallback objref);
      boolean othello(in ChatCallback objref, in string cmd);
   };
};
