module ChatApp {
   interface ChatCallback {
      void callback(in string message);
   };
   interface Chat {
      boolean say(in ChatCallback objref, in string message);
      boolean join(in ChatCallback objrer, in string nickname);
   };
};
